### PR TITLE
Fix #10950: Replace raw RuntimeException on reactor cycle with ProjectBuildingExc…

### LINKED ISSUE #10950: DeafultProjectBuilder throws raw RuntimeException
### Affected version

HEAD

### Bug description

At the very least this should be a specific subclass of runtime exception, but given that this likely indicates a  problem in the input POMs it should probably be a checked exception.

```
                if (cycle != null) {
                    throw new RuntimeException(new ProjectCycleException(
                            "The projects in the reactor contain a cyclic reference: " + cycle.getMessage(),
                            (CycleDetectedException) cycle.getException()));
                }

```

### PR DESCRIPTION
**Pull request by arturobernalg**
…eption.

When a reactor dependency cycle is detected, wrap the underlying org.codehaus.plexus.util.dag.CycleDetectedException in a new ProjectCycleException and throw a checked ProjectBuildingException (as declared by ProjectBuilder) instead of a raw RuntimeException.

Keep non-cycle model problems on the existing ProjectBuildingException(results) path.

Following this checklist to help us incorporate your
contribution quickly and easily:

- [X ] Your pull request should address just one issue, without pulling in other changes.
- [X ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [X ] Each commit in the pull request should have a meaningful subject line and body.
  Note that commits might be squashed by a maintainer on merge.
- [ ] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
  This may not always be possible but is a best-practice.
- [X ] Run `mvn verify` to make sure basic checks pass.
  A more thorough check will be performed on your pull request automatically.
- [ X] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

File: impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java [hunk 1]
```diff
@@ -492,10 +492,22 @@ List<ProjectBuildingResult> build(List<File> pomFiles, boolean recursive) throws
                         .findAny()
                         .orElse(null);
                 if (cycle != null) {
-                    throw new RuntimeException(new ProjectCycleException(
+                    final CycleDetectedException cde = (CycleDetectedException) cycle.getException();
+
+                    final ProjectCycleException pce = new ProjectCycleException(
+                            "The projects in the reactor contain a cyclic reference: " + cycle.getMessage(), cde);
+
+                    // If you can resolve these from the problem/result, set them; otherwise leave null.
```
Comment (elharo) [inline impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java]: This comment doesn't seem right. They can't be set here.

File: impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java [hunk 2]
```diff
@@ -492,10 +492,22 @@ List<ProjectBuildingResult> build(List<File> pomFiles, boolean recursive) throws
...
+                    final String projectId = null;
+                    final File pomFile = null;
+
+                    throw new ProjectBuildingException(
+                            projectId,
                             "The projects in the reactor contain a cyclic reference: " + cycle.getMessage(),
-                            (CycleDetectedException) cycle.getException()));
+                            pomFile,
+                            pce);
```
Comment (elharo) [inline impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java]: I'm not clear why pce was created. Could you just pass the cde here?

**Review by gnodet — APPROVED** [review]

File: impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java [hunk 3]
```diff
@@ -492,10 +491,14 @@ List<ProjectBuildingResult> build(List<File> pomFiles, boolean recursive) throws
                         .findAny()
                         .orElse(null);
                 if (cycle != null) {
-                    throw new RuntimeException(new ProjectCycleException(
+                    final CycleDetectedException cde = (CycleDetectedException) cycle.getException();
```
Comment (elharo) [inline impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java:494]: The wrapping still smells like something's not quite right. The code is quite complex, and it might be simpler without the lambda, but either way we really should be able to just throw the CycleDetectedException. This is not a public method so we can easily add that to the method signature. It's also possible CycleDetectedException should be a subclass of ProjectBuildingException.

**Review by elharo — APPROVED** [review]
I suspect CycleDetectedException should have been a subclass of ProjectBuildingException, but that would require an API change so this is good enough forn now
