### PR TITLE
[3.9.x] MavenPluginJavaPrerequisiteChecker: Handle 8/1.8 Java version in ranges as well

### LINKED ISSUE #11575: Java prerequisites for Maven Plugins fails for Java 8
### Affected version

3.9.12

### Bug description

[WARNING] Ignoring incompatible plugin version 0.4.6: 
The plugin eu.maveniverse.maven.plugins:nisse-plugin3:0.4.6 has unmet prerequisites: 
	Required Java version [8,) is not met by current version: 1.8.0_462

### PR DESCRIPTION
**Pull request by cstamas**
Java is consistent when reporting versions, but users are not. No need to go below 1.8, as Maven 3.9 is Java 8 only. This PR makes "8/1.8" work for ranges as well, not only for standalone version.

Fixes #11575

### CODE REVIEW

File: maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteChecker.java [hunk 1]
```diff
@@ -47,9 +47,13 @@ public void accept(PluginDescriptor pluginDescriptor) {
     }
 
     boolean matchesVersion(String requiredVersion, String currentVersion) {
+        // Java 8 is consistent: it will always say "1.8...". Users are not consistent.
+        if (!requiredVersion.contains("1.8") && currentVersion.startsWith("1.8")) {
+            currentVersion = currentVersion.substring(2);
+        }
         VersionConstraint constraint;
         try {
-            constraint = versionScheme.parseVersionConstraint(requiredVersion.equals("8") ? "1.8" : requiredVersion);
```
Comment (Bukama) [inline maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteChecker.java:52]: two lines above you substring `currentVersion` here it's about `requiredVersion`. Is it intended or are you accidently mixing variables?

File: maven-core/src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java [hunk 2]
```diff
@@ -30,7 +30,22 @@ public class MavenPluginJavaPrerequisiteCheckerTest {
     public void testMatchesVersion() {
```
Comment (Bukama) [inline maven-core/src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java]: Use Parameterized tests here

Comment (cstamas) [reply maven-core/src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java]: Did the change as you asked, but now fails with checkstyle:
```
Error:  src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java:[67,19] (design) VisibilityModifier: Variable 'requiredVersion' must be private and have accessor methods.
Error:  src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java:[70,19] (design) VisibilityModifier: Variable 'currentVersion' must be private and have accessor methods.
Error:  src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java:[73,20] (design) VisibilityModifier: Variable 'expected' must be private and have accessor methods.
```

Comment (cstamas) [reply maven-core/src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java]: Clearly the two are not aligned: as if I make field private or just non-public, I get
```
Cannot set parameter 'requiredVersion'. Ensure that the field 'requiredVersion' is public.
```
So one want this, other want that.

Comment (slawekjaranowski) [reply maven-core/src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java]: do it simple, you can try to add suppress for checkstyle, by the way I'm working on move test to JUnit 5 in #11547

**Comment by kwin** [comment]
What about Maven 4? Shouldn't the versions be interpreted the same?

**Comment by cstamas** [comment]
> What about Maven 4? Shouldn't the versions be interpreted the same?

Maven4 is Java 17+, hence it does not need to handle 8/1.8
