### PR TITLE
Fix special characters in .mvn/jvm.config (fix #11363, #11485 and #11486)

### LINKED ISSUE #11363: [REGRESSION] Maven 4 fails to parse pipe symbols in `.mvn/jvm.config`
### Affected version

4.0.0-rc-4

### Bug description

To reproduce, createe `.mvn/jvm.config` and add:

```env
-Dhttp.nonProxyHosts=de|*.de|my.company.mirror.de
```

Then execute Maven and find this:

```bash
❯ ./mvnw clean verify -Prun-its
$HOME/.m2/wrapper/dists/apache-maven-4.0.0-rc-4/9c77e524/bin/mvn: line 265: *.de: command not found
$HOME/.m2/wrapper/dists/apache-maven-4.0.0-rc-4/9c77e524/bin/mvn: line 265: my.company.mirror.de: command not found
Usage: java [java options...] <application> [application arguments...]

Where <application> is one of:
  <mainclass>                to execute the main method of a compiled main class
  -jar <jarfile>.jar         to execute the main class of a JAR archive
  -m <module>[/<mainclass>]  to execute the main class of a module
  <sourcefile>.java          to compile and execute a source-file program

Where key java options include:
  --class-path <class path>
    where <class path> is a list of directories and JAR archives to search for class files, separated by ":"
  --module-path <module path>
    where <module path> is a list of directories and JAR archives to search for modules, separated by ":"
  -version
    to print product version to the error stream and exit

For additional help on usage:           java --help
For an interactive Java environment:    jshell
```

This only happens on Maven 4, not on Maven 3.

### PR DESCRIPTION
**Pull request by gnodet**
This PR fixes multiple related issues with special character handling in `.mvn/jvm.config` files by unifying the parsing approach to use `JvmConfigParser.java` on both Unix and Windows platforms.

## Issues Fixed

- **MNG-11363**: Pipe symbols (`|`) in jvm.config cause shell parsing errors
- **MNG-11485**: Non-POSIX `xargs -0` fails on AIX, FreeBSD, and other systems  
- **MNG-11486**: `sed` command fails when paths contain `@` symbols

## Related PRs

- Supersedes #11489 (MNG-11485: POSIX compliance)
- Supersedes #11499 (MNG-11486: @ symbols in paths)

## Solution

Instead of using complex shell/batch script parsing with `awk`, `sed`, and `xargs`, this PR uses the existing `JvmConfigParser.java` on both platforms:

### Unix (`mvn`)
- Compiles `JvmConfigParser.java` to a temporary directory
- Runs the parser to process `jvm.config`
- Cleans up temporary files
- Falls back gracefully if compilation fails

### Windows (`mvn.cmd`)
- Already used `JvmConfigParser.java` (no functional changes)
- Removed debug output
- Updated comments

## Benefits

✅ **Correctness**: Handles all edge cases reliably (pipes, quotes, `@`, etc.)  
✅ **POSIX Compliance**: No non-standard tools needed (`xargs -0`, GNU-specific `awk`/`sed`)  
✅ **Maintainability**: Single implementation for both platforms  
✅ **Consistency**: Same behavior on Windows and Unix

## Test Coverage

- ✅ `MavenITgh11363PipeSymbolsInJvmConfigTest` - Tests pipe symbols in jvm.config
- ✅ `MavenITgh11485AtSignInJvmConfigTest` - Tests `@` symbols in jvm.config (important for Jenkins workspaces like `workspace/project_PR-350@2`)

## Performance Impact

Unix script is ~200ms slower (320ms → 520ms for `mvn -v`) due to Java compilation, but this is acceptable for the correctness and maintainability benefits.

### Pipe symbols (MNG-11363)
```properties
# .mvn/jvm.config
-Dhttp.nonProxyHosts=de|*.de|my.company.mirror.de
```
✅ Now works correctly: `de|*.de|my.company.mirror.de`

### Quoted pipes
```properties
# .mvn/jvm.config
-Dprop.with.pipes="value|with|pipes"
```
✅ Now works correctly: `value|with|pipes`

### @ symbols in paths (MNG-11486)
```properties
# .mvn/jvm.config
-Dtest.path=${MAVEN_PROJECTBASEDIR}/workspace@2/test
```
✅ Now works correctly: `/path/to/workspace@2/test`

### CODE REVIEW

**Comment by gnodet** [comment]
Updated all commit messages to use `[gh-11363]` instead of `[MNG-11363]` to follow the correct issue reference format.

**Comment by gnodet** [comment]
Fixed the integration test failures. The issue was that the previous implementation was escaping pipes in `concat_lines` but then using `eval` which still interpreted them as shell operators.

The updated fix:
1. Uses `awk` to escape unquoted pipes with backslashes in the `concat_lines` function
2. Uses `eval` with the escaped MAVEN_OPTS to properly handle the pipes

This ensures that pipe symbols in JVM arguments (like `-Dhttp.nonProxyHosts=de|*.de`) are treated as literal characters rather than shell pipe operators.

All previously failing tests now pass:
- ✅ MavenITgh11363PipeSymbolsInJvmConfigTest
- ✅ MavenITmng4559MultipleJvmArgsTest
- ✅ MavenITmng5889FindBasedir
- ✅ MavenITmng6223FindBasedir
- ✅ MavenITmng8598JvmConfigSubstitutionTest

**Comment by gnodet** [comment]
> One nit: why not use same Java helper on all platforms?

Answered in the description.
When doing perfs measurements, running `mvn -v` went from 320 ms (using awk) to 520 ms (using the java parser).
So I don't think it's better to keep two separate solutions at this point.

**Comment by gnodet** [comment]
The ITs are unstable, especially on windows...

File: apache-maven/src/assembly/maven/bin/mvn [hunk 1]
```diff
@@ -166,30 +166,55 @@ find_file_argument_basedir() {
...
-      arg=$(echo "$arg" | sed \
-        -e "s@\${MAVEN_PROJECTBASEDIR}@$MAVEN_PROJECTBASEDIR@g" \
-        -e "s@\$MAVEN_PROJECTBASEDIR@$MAVEN_PROJECTBASEDIR@g")
-
-      echo "$arg"
-    done | \
-    tr '\n' ' '
+    # Compile and run JvmConfigParser
+    # Use a temporary directory for compilation to avoid conflicts
+    jvm_parser_dir="${TMPDIR:-/tmp}/mvn-jvm-parser-$$"
```
Comment (bmarwell) [inline apache-maven/src/assembly/maven/bin/mvn]: ID reuse -- is ist still a thing on some Unixes? I do not know, but I guess this should be fine.

File: apache-maven/src/assembly/maven/bin/mvn [hunk 2]
```diff
@@ -166,30 +166,55 @@ find_file_argument_basedir() {
...
+
+    javac_cmd="${JAVACMD%java*}javac"
+    if [ ! -x "$javac_cmd" ]; then
+      # Try to find javac in JAVA_HOME
+      if [ -n "$JAVA_HOME" ]; then
+        javac_cmd="$JAVA_HOME/bin/javac"
+      fi
+    fi
+
+    "$javac_cmd" -d "$jvm_parser_dir" "$MAVEN_HOME/bin/JvmConfigParser.java" >/dev/null 2>&1
```
Comment (bmarwell) [inline apache-maven/src/assembly/maven/bin/mvn]: Why `javac`? We are on 17, we can just do `java JvmConfigParser.java`

File: apache-maven/src/assembly/maven/bin/JvmConfigParser.java [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+                List<String> parsed = parseArguments(line);
+
+                // Append each argument quoted
+                for (String arg : parsed) {
+                    if (result.length() > 0) {
+                        result.append(' ');
+                    }
+                    result.append('"').append(arg).append('"');
+                }
+            });
```
Comment (bmarwell) [inline apache-maven/src/assembly/maven/bin/JvmConfigParser.java]: Long lambdas are unreadable, and also impact performance. I would use a traditional for loop (extracted to a method) here and put the contents into a new method.
I do not know how much faster it is, but besides performance, lambdas are also harder to identify in the debugger.

File: apache-maven/src/assembly/maven/bin/JvmConfigParser.java [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+
+            System.out.print(result.toString());
+            System.out.flush(); // Ensure output is flushed before exit (important on Windows)
```
Comment (bmarwell) [inline apache-maven/src/assembly/maven/bin/JvmConfigParser.java]: imo the comment is not needed

File: apache-maven/src/assembly/maven/bin/mvn.cmd [hunk 5]
```diff
@@ -177,38 +177,25 @@ cd /d "%EXEC_DIR%"
...
-    )
-)
-@endlocal & set JVM_CONFIG_MAVEN_OPTS=%JVM_CONFIG_MAVEN_OPTS%
+rem Use Java to parse jvm.config to avoid batch script parsing issues with special characters
+rem This handles pipes, quotes, @, and other special characters correctly
+rem Use random temp directory to avoid conflicts between different Maven invocations
+set "JVM_CONFIG_PARSER_DIR=%TEMP%\mvn-jvm-parser-%RANDOM%-%RANDOM%"
+mkdir "%JVM_CONFIG_PARSER_DIR%"
+set "JVM_CONFIG_TEMP=%TEMP%\mvn-jvm-config-%RANDOM%.txt"
+"%JAVACMD:java.exe=javac.exe%" -d "%JVM_CONFIG_PARSER_DIR%" "%MAVEN_HOME%\bin\JvmConfigParser.java" >nul 2>&1
```
Comment (bmarwell) [inline apache-maven/src/assembly/maven/bin/mvn.cmd]: Same as on posix/unix: why run `javac`? We are on 17 and can easily run single-source files using `java`.

File: apache-maven/src/assembly/maven/bin/JvmConfigParser.java [hunk 6]
```diff
@@ -0,0 +1,132 @@
...
+        } catch (IOException e) {
+            System.err.println("Error reading jvm.config: " + e.getMessage());
+            System.exit(1);
```
Comment (bmarwell) [inline apache-maven/src/assembly/maven/bin/JvmConfigParser.java]: This system.exit makes testing a potential IOException problematic

**Review by bmarwell — APPROVED** [review]
