### PR TITLE
Avoid parsing MAVEN_OPTS (master/4.x)

### LINKED ISSUE #10937: Quoted pipes in MAVEN_OPTS throw errors in 3.9.10+, 4.0.0-rc
### Affected version

3.9.10, 3.9.11, 4.0.0-rc-4

### Bug description

Environment: Windows Server 2019
Maven: 3.9.10, invoked via `mvnw.cmd` wrapper

---

Minimal example (3.9.10):

```
$env:MAVEN_OPTS='"-Dfoo=bar|baz"'
mvn
```

On 4.0.0-rc-4, this requires an additional `.mvn/jvm.config` file to exist in the project directory or the `--yjp` arg. Same fundamental issue, different trigger in the script.

---

Consider this `MAVEN_OPTS` environment variable (used on a CI server with restricted network access):

```
-Dhttps.proxyHost=192.0.2.4 -Dhttps.proxyPort=8080 "-Dhttps.nonProxyHosts=*.example.com|*.example.net" -Dhttp.proxyHost=192.0.2.4 -Dhttp.proxyPort=8080 "-Dhttps.nonProxyHosts=*.example.com|*.example.net"
```

Here we have a few values that require the pipe `|` as a separator. This requires quoting to correctly process as a value and not a command line pipe. This works in 3.9.9.

MNG-8248 (https://github.com/apache/maven/issues/10391) made a change that causes the `mvnw.cmd` script to attempt to prepend a value to `MAVEN_OPTS`:

```
set "MAVEN_OPTS=--enable-native-access=ALL-UNNAMED %MAVEN_OPTS%"
```

Unfortunately, the style used here wraps `%MAVEN_OPTS%` in further quotes, and due to the nature of Windows batch processing the `%%` variable is substituted very early, before the quotes are processed. Effectively, this transforms the above example so that the pipes are now *outside* the quotes, which results in the error:

```
'*.example.net' is not recognized as an internal or external command,
operable program or batch file.
```

---

Specifically, this seems to be the responsible section:

https://github.com/apache/maven/blob/d9f0a4828a49e90de198addb5ce620c6369d6671/apache-maven/src/bin/mvn.cmd#L175-L179

---

I can think of a few potential ways to fix this. I'm unsure which one would be most suitable for this project, so I'll list them here:

1. Don't quote the `set` arguments. Simply using `set MAVEN_OPTS=--enable-native-access=ALL-UNNAMED %MAVEN_OPTS%` instead seems to work, though I can't guarantee that the lack of quoting won't cause other issues. Also, the other `set`s in the same file seem to use the same quoted style so perhaps this is in some style guide somewhere..?

2. Introduce a new variable and don't manipulate `MAVEN_OPTS`. e.g. `set "USE_NATIVE_ACCESS=--enable-native-access=ALL-UNNAMED"` and later insert `%USE_NATIVE_ACCESS%` into the same command ahead of `MAVEN_OPTS`, which would result in the same final command. Alternatively, introduce some kind of `EXTRA_OPTS` variable that is internal to the file -- the key here is to not do anything that would parse `MAVEN_OPTS` (or other external variables) before they are used.

3. Use delayed expansion instead. `setlocal EnableDelayedExpansion` and then use `set "MAVEN_OPTS=--enable-native-access=ALL-UNNAMED !MAVEN_OPTS!"` is fine, because it expands the inner `MAVEN_OPTS` after parse where `|` has special meaning.

### PR DESCRIPTION
**Pull request by BobVul**
Fixes #10937 by introducing an additional INTERNAL_MAVEN_OPTS for any arguments that need to be inserted by the script. Parsing the externally-defined MAVEN_OPTS variable can lead to incorrect processing of quotes and special characters, so use the separate variable to avoid doing so.

Additionally JVM_CONFIG_MAVEN_OPTS is introduced as its own variable to preserve the append behaviour.

Specifically, this fixes this case:

```
$env:MAVEN_OPTS='"-Dfoo=bar|baz"'
mkdir .mvn
New-Item .mvn\jvm.config
mvn
```

by implementing proposed fix 2 from https://github.com/apache/maven/issues/10937

The related fix for 3.9.x branch is in PR #10969

---

Following this checklist to help us incorporate your
contribution quickly and easily:

- [x] Your pull request should address just one issue, without pulling in other changes.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Each commit in the pull request should have a meaningful subject line and body.
  Note that commits might be squashed by a maintainer on merge.
- [x] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
  This may not always be possible but is a best-practice.
- [x] Run `mvn verify` to make sure basic checks pass.
  A more thorough check will be performed on your pull request automatically.
- [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

File: its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh10937QuotedPipesInMavenOptsTest.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+import java.util.Properties;
+
+import org.junit.jupiter.api.Test;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+/**
+ * This is a test set for <a href="https://github.com/apache/maven/issues/10937">gh-10937</a>.
+ */
+class MavenITgh10937QuotedPipesInMavenOptsTest extends AbstractMavenIntegrationTestCase {
```
Comment (slawekjaranowski) [inline its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh10937QuotedPipesInMavenOptsTest.java:31]: it is not similar to `MavenITmng4559SpacesInJvmOptsTest` if yes - we can simple extend it instead of creating next test
We can add description to test that also check case from issue xxx

Comment (BobVul) [reply its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh10937QuotedPipesInMavenOptsTest.java:31]: They're very similar, yea. I used the 4559 one as a template.

However, the 4559 test is only defined in 4.x. When I create the tests for 3.9.x, should I then keep that set separate?

Comment (slawekjaranowski) [reply its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh10937QuotedPipesInMavenOptsTest.java:31]: ok, we can have a new test

**Comment by BobVul** [comment]
Looks like in 4.x the bash script also changed, such that it now `eval`s the command and introduces a similar pipe parsing error in a completely different way.

The changes made here (purely to the Windows .cmd!) should have no impact on that, but the new tests do expose that issue.

I'll consolidate findings/discussion back in issue #10937 but I'm honestly not too sure what to do here -- complex bash scripts are not my forte.

**Comment by BobVul** [comment]
@gnodet Since you made the original change in #2213, could I run this by you, as I'm a bit unsure.

The existing behaviour is:
1. The change there updated `concat_lines` to perform more advanced parsing of `jvm.config`.
2. In the process it runs the lines through `xargs`, which processes quotes specially, in the process stripping them from the input
3. Later, quotes are added back in if the line is not surrounded by them and contains spaces (i.e. first and last char only)

But the behaviour seen with pipes specifically is that the quotes are being stripped but not added back in. i.e. `-Dopt="foo|bar"` is transformed into `-Dopt=foo|bar` and causing problems on Linux. I can see two ways of handling this:

1. Add pipes to the "check for spaces" bit, which will then re-surround the entire line in quotes. This would probably work but seems a tad hacky?
2. Change out the `xargs -n 1` command for `tr '\n' '\0' | xargs -n 1 -0`, i.e. use xargs in NUL mode. This prevents xargs from handling quotes specially, and therefore quotes are not stripped from the input. However, this also means the code that re-adds quotes must be removed else it will cause e.g. `-Dopt="foo bar"` to become `"-Dopt="foo bar""` which effectively leaves the space unquoted again (much like the original issue on Windows!). I think this is probably fine since in this case `xargs` won't strip initial quotes, though it does force the user to add quotes manually.

I'm leaning towards using option 2, but I'm not familiar enough with either this area of code nor bash to be certain that it won't cause other issues. Do you have any suggestions here?

Proposed new `concat_lines`:

```bash
concat_lines() {
  if [ -f "$1" ]; then
    # First convert all CR to LF using tr
    tr '\r' '\n' < "$1" | \
    sed -e '/^$/d' -e 's/#.*$//' | \
    # Replace LF with NUL for xargs
    tr '\n' '\0' | \
    # Split into words and process each argument
    # Use -0 with NUL to avoid special behaviour on quotes
    xargs -n 1 -0 | \
    while read -r arg; do
      # Replace variables first
      arg=$(echo "$arg" | sed \
        -e "s@\${MAVEN_PROJECTBASEDIR}@$MAVEN_PROJECTBASEDIR@g" \
        -e "s@\$MAVEN_PROJECTBASEDIR@$MAVEN_PROJECTBASEDIR@g")

      echo "$arg"
    done | \
    tr '\n' ' '
  fi
}
```

**Review by gnodet — APPROVED** [review]
LGTM, thx for this nice patch ! I'll do the backport to `maven-4.0.x` branch.

**Comment by slawekjaranowski** [comment]
> Should the 3.9.x IT also be merged? [apache/maven-integration-testing#407](https://github.com/apache/maven-integration-testing/pull/407)

should 😄 done
