### PR TITLE
GH-11181 Metaversion validation and lax conflict detection

### LINKED ISSUE #11181: Extensions defined in any supported extensions.xml does not support meta versions
### New feature, improvement proposal

I think this is wrong. IMHO it should be:
* project `.mvn/extensions.xml` should not allow (as now)
* user wide `~/.m2/extensions.xml` should allow
* system wide `$MAVEN_HOME/conf/extensions.xml` am on edge here: yes? no?

### PR DESCRIPTION
**Pull request by cstamas**
Changes:
* validate for metaversions in extensions XML
* conflict detection should not report conflict for same V
* support for metaversions during extension resolution

Fixes #11181

### CODE REVIEW

File: impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java [hunk 1]
```diff
@@ -526,23 +527,37 @@ protected List<CoreExtension> readCoreExtensionsDescriptorFromFile(Path extensio
...
     protected List<CoreExtension> validateCoreExtensionsDescriptorFromFile(
-            Path extensionFile, List<CoreExtension> coreExtensions) {
+            Path extensionFile, List<CoreExtension> coreExtensions, boolean allowMetaVersions) {
         Map<String, List<InputLocation>> gasLocations = new HashMap<>();
+        Map<String, List<InputLocation>> metaVersionLocations = new HashMap<>();
         for (CoreExtension coreExtension : coreExtensions) {
             String ga = coreExtension.getGroupId() + ":" + coreExtension.getArtifactId();
             InputLocation location = coreExtension.getLocation("");
             gasLocations.computeIfAbsent(ga, k -> new ArrayList<>()).add(location);
+            // TODO: metaversions could be extensible enum with these two values out of the box
```
Comment (cstamas) [inline impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java:537]: @gnodet maybe not extensible enum right now, but where would be their proper place? Maybe not even in API (to draw attention) for start, just some constants somewhere?

File: its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh11181CoreExtensionsMetaVersionsTest.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+                .resolve("pw-metaversion-is-invalid");
+        Verifier verifier = newVerifier(testDir.toString());
+        verifier.setUserHomeDirectory(testDir.resolve("HOME"));
+        verifier.setAutoclean(false);
+        verifier.addCliArgument("validate");
+        try {
+            verifier.execute();
+            fail("Expected VerificationException");
+        } catch (VerificationException e) {
+            // there is no even log; this is very early failure
```
Comment (elharo) [inline its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh11181CoreExtensionsMetaVersionsTest.java]: not even a log
