### PR TITLE
Fix #10939: DefaultModelXmlFactory: make location tracking opt-in—disabled by def…

### LINKED ISSUE #10939: Location tracking can not be disabled through the DefaultModelXmlFactory
### Affected version

4.0.0-rc-4

### Bug description

While working on moving the `maven-help-plugin` to Maven 4 I noticed we no longer use the `MavenStaxWriter` directly. This is now done through the `DefaultModelXmlFactory`. 

The `DefaultModelXmlFactory` however does not provide a way to define `addLocationInformation` on the `MavenStaxWriter`. The `XmlWriterRequest` defines a way to set the `InputLocationFormatter` which is related to the `addLocationInformation`. The formatter is (currently) only used when locationtracking is requested.

My suggestion would be:

- Set `addLocationInformation` to `false` by default in `DefaultModelXmlFactory`.
- If the `XmlWriterRequest` specifies an `InputLocationFormatter`, set `addLocationInformation` to `true` and apply the formatter.

### PR DESCRIPTION
**Pull request by arturobernalg**
…ault, enabled when an InputLocationFormatter is provided.

Adapt formatter to Function<InputLocation,String> and write to the actually opened stream for path output. Fixes #10939.

Following this checklist to help us incorporate your
contribution quickly and easily:

- [ X] Your pull request should address just one issue, without pulling in other changes.
- [ X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ X] Each commit in the pull request should have a meaningful subject line and body.
  Note that commits might be squashed by a maintainer on merge.
- [ X] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
  This may not always be possible but is a best-practice.
- [ X] Run `mvn verify` to make sure basic checks pass.
  A more thorough check will be performed on your pull request automatically.
- [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

====

Supersedes #10940

### CODE REVIEW

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 1]
```diff
@@ -115,32 +117,42 @@ private Model doRead(XmlReaderRequest request) throws XmlReaderException {
...
         if (writer == null && outputStream == null && path == null) {
             throw new IllegalArgumentException("writer, outputStream or path must be non null");
         }
+
         try {
-            MavenStaxWriter w = new MavenStaxWriter();
-            if (inputLocationFormatter != null) {
-                w.setStringFormatter((Function) inputLocationFormatter);
+            // OFF by default
+            final MavenStaxWriter xml = new MavenStaxWriter();
```
Comment (elharo) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: xml --> xmlWriter

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 2]
```diff
@@ -115,32 +117,42 @@ private Model doRead(XmlReaderRequest request) throws XmlReaderException {
...
+                xml.write(outputStream, content);
             } else {
                 try (OutputStream os = Files.newOutputStream(path)) {
-                    w.write(os, content);
+                    xml.write(os, content);
                 }
             }
         } catch (Exception e) {
-            throw new XmlWriterException("Unable to write model: " + getMessage(e), getLocation(e), e);
+            throw new XmlWriterException("Unable to write model " + getMessage(e), getLocation(e), e);
```
Comment (elharo) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: This line doesn't need to be changed in this PR

File: impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java [hunk 3]
```diff
@@ -122,4 +125,65 @@ void testMalformedModelVersion() throws Exception {
...
+        StringWriter out = new StringWriter();
+        factory.write(XmlWriterRequest.<Model>builder()
+                .writer(out)
+                .content(model)
+                // no formatter -> tracking should be OFF
+                .build());
+
+        String result = out.toString();
+        // Heuristic: when tracking is off there should be no location output (no comments)
+        assertTrue(!result.contains("<!--"), "Expected no XML comments when location tracking is disabled");
```
Comment (elharo) [inline impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java]: assretFalse

File: impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java [hunk 4]
```diff
@@ -122,4 +125,65 @@ void testMalformedModelVersion() throws Exception {
...
+        // And certainly not our marker
+        assertTrue(!result.contains("LOC_MARK"), "Unexpected marker found in output");
```
Comment (elharo) [inline impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java]: This isn't needed; or maybe keep this and get rid of the previous assert; if so, assertFalse

**Review by elharo — CHANGES_REQUESTED** [review]
There seem to be a lot of changes here that have nothing to do with teh purpose of thiks PR. Try to keep the changes more focused

**Comment by arturobernalg** [comment]
please do another pass

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 5]
```diff
@@ -115,28 +117,38 @@ private Model doRead(XmlReaderRequest request) throws XmlReaderException {
...
-    public void write(XmlWriterRequest<Model> request) throws XmlWriterException {
-        requireNonNull(request, "request");
-        Model content = requireNonNull(request.getContent(), "content");
-        Path path = request.getPath();
-        OutputStream outputStream = request.getOutputStream();
-        Writer writer = request.getWriter();
-        Function<Object, String> inputLocationFormatter = request.getInputLocationFormatter();
+    public void write(final XmlWriterRequest<Model> request) throws XmlWriterException {
+        Objects.requireNonNull(request, "request can not be null");
+        final Model content = Objects.requireNonNull(request.getContent(), "content can not be null");
```
Comment (elharo) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: Is there a reason to make all these variables final in this PR?

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 6]
```diff
@@ -115,28 +117,38 @@ private Model doRead(XmlReaderRequest request) throws XmlReaderException {
...
+
         if (writer == null && outputStream == null && path == null) {
             throw new IllegalArgumentException("writer, outputStream or path must be non null");
         }
+
         try {
-            MavenStaxWriter w = new MavenStaxWriter();
-            if (inputLocationFormatter != null) {
-                w.setStringFormatter((Function) inputLocationFormatter);
+            // OFF by default
```
Comment (elharo) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: what is off by default?

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 7]
```diff
@@ -115,28 +117,38 @@ private Model doRead(XmlReaderRequest request) throws XmlReaderException {
...
+            final MavenStaxWriter xmlWriter = new MavenStaxWriter();
+            xmlWriter.setAddLocationInformation(false);
+
+            // Opt-in when a formatter is provided; adapt to the required type
```
Comment (elharo) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: "Optt-in" feels like the wrong language here. No human is making a choice

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 8]
```diff
@@ -115,28 +117,38 @@ private Model doRead(XmlReaderRequest request) throws XmlReaderException {
...
+            final Function<Object, String> fmt = request.getInputLocationFormatter();
```
Comment (elharo) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: fmt --> formatter

File: impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java [hunk 9]
```diff
@@ -122,4 +126,63 @@ void testMalformedModelVersion() throws Exception {
...
+
+        StringWriter out = new StringWriter();
+        factory.write(XmlWriterRequest.<Model>builder()
+                .writer(out)
+                .content(model)
+                // no formatter -> tracking should be OFF
+                .build());
+
+        String result = out.toString();
+        // And certainly not our marker
```
Comment (elharo) [inline impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java]: rewrite comment

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 10]
```diff
@@ -121,22 +122,29 @@ public void write(XmlWriterRequest<Model> request) throws XmlWriterException {
...
         }
+
         try {
-            MavenStaxWriter w = new MavenStaxWriter();
-            if (inputLocationFormatter != null) {
-                w.setStringFormatter((Function) inputLocationFormatter);
+            final MavenStaxWriter xmlWriter = new MavenStaxWriter();
+            xmlWriter.setAddLocationInformation(false);
+
+            final Function<Object, String> fmtformatter = request.getInputLocationFormatter();
```
Comment (elharo) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: what is an fmtformatter? just formatter should be OK, or maybe inputLocationFormatter

Comment (arturobernalg) [reply impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]: > what is an fmtformatter? just formatter should be OK, or maybe inputLocationFormatter

Sorry. type.  Fixed

**Review by gnodet — APPROVED** [review]

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 11]
```diff
@@ -121,22 +122,29 @@ public void write(XmlWriterRequest<Model> request) throws XmlWriterException {
...
+
         if (writer == null && outputStream == null && path == null) {
             throw new IllegalArgumentException("writer, outputStream or path must be non null");
         }
+
         try {
-            MavenStaxWriter w = new MavenStaxWriter();
-            if (inputLocationFormatter != null) {
-                w.setStringFormatter((Function) inputLocationFormatter);
+            final MavenStaxWriter xmlWriter = new MavenStaxWriter();
```
Comment (gnodet) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]:
```suggestion
            MavenStaxWriter xmlWriter = new MavenStaxWriter();
```

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 12]
```diff
@@ -121,22 +122,29 @@ public void write(XmlWriterRequest<Model> request) throws XmlWriterException {
...
+            xmlWriter.setAddLocationInformation(false);
+
+            final Function<Object, String> formatter = request.getInputLocationFormatter();
```
Comment (gnodet) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]:
```suggestion
            Function<Object, String> formatter = request.getInputLocationFormatter();
```

File: impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java [hunk 13]
```diff
@@ -121,22 +122,29 @@ public void write(XmlWriterRequest<Model> request) throws XmlWriterException {
...
+            if (formatter != null) {
+                xmlWriter.setAddLocationInformation(true);
+                final Function<InputLocation, String> adapter = formatter::apply;
```
Comment (gnodet) [inline impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java]:
```suggestion
                Function<InputLocation, String> adapter = formatter::apply;
```

**Review by gnodet — APPROVED** [review]

**Comment by gnodet** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|master|[](https://github.com/apache/maven/pull/11198)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
